export default {
  SET_POPULAR_RECIPES: 'SET_POPULAR_RECIPES',
  SET_SEARCH_RECIPES: 'SET_SEARCH_RECIPES',
  SET_CATEGORIES: 'SET_CATEGORIES',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
  CHANGE_TITLE_VALUE: 'CHANGE_TITLE_VALUE',
  SET_CATEGORY_RECIPES: 'SET_CATEGORY_RECIPES',
  CHANGE_RECIPE_LIST: 'CHANGE_RECIPE_LIST',
  SET_MODAL_RECIPE: 'SET_MODAL_RECIPE',
  SET_FAVORITES: 'SET_FAVORITES',
  TOGGLE_PRELOADER: 'TOGGLE_PRELOADER',
}