export default {
  SET_POPULAR_RECIPES: 'SET_POPULAR_RECIPES',
  SET_CURRENT_RECIPES: 'SET_CURRENT_RECIPES',
  SET_CATEGORIES: 'SET_CATEGORIES',
  TOGGLE_SEARCH_VALUE: 'TOGGLE_SEARCH_VALUE',
  CHANGE_SEARCH_TITLE_VALUE: 'CHANGE_SEARCH_TITLE_VALUE',
  CHANGE_POPULAR_TITLE_VALUE: 'CHANGE_POPULAR_TITLE_VALUE'
}